import { Container, Flex, Heading, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack css={{ width: "100%" }}>
        <Flex direction={"column"} css={{ gap: "4rem" }}>
          <Heading>eggjam.io</Heading>
        </Flex>
      </VStack>
    </Container>
  );
};

export default Home;
